### ISSUE TITLE
Add a community button (either in the Topbar or under the list of submenus)

### ISSUE THREAD

**Issue by ni1chigo2115** [Bl4Cc4t/GoodTwitter2#424]
A community feature has been added to Twitter on a trial basis.
This seems to be a feature that allows users to join a group to limit the scope of tweets they can send and view. However, GT2 can only display it, but there seems to be no link to access it. Please add it.
![gt2_community](https://user-images.githubusercontent.com/23652237/160235018-e49eec67-4fe9-40c4-ba21-c2d5077503ac.jpg)

**Comment by Bl4Cc4t** [comment]
Since I don't have that feature yet on my end, I am not sure if my implementation is correct.
Can you please check if the "communities" button is a link that leads to "/i/communities?"

**Comment by ni1chigo2115** [comment]
I tested the dev version.
Hmmm...the button doesn't seem to be showing up in the first place.

**Comment by rekvui** [comment]
https://twitter.com/i/communities

**Comment by Bl4Cc4t** [comment]
great, thanks for checking.
then in theory it should be working, I'll probably release the next version tomorrow

**Comment by rekvui** [comment]
great, thank you!

**Comment by ni1chigo2115** [comment]
thank you!

**Comment by Bl4Cc4t** [comment]
sorry, took a bit longer to release. it would be really useful if you could test if the button appears in the submenu since I still do not have it yet!

**Comment by rekvui** [comment]
unfortunately, it's still not showing up
![image](https://user-images.githubusercontent.com/93687310/161641871-ddd0841d-0e9d-489b-a2cc-57e0e2f42568.png)

**Comment by maxymax13** [comment]
you can join or make a community to have the button show so you can make the feature work

**Comment by rekvui** [comment]
I have already joined some communities
the problem is that the button itself still doesn't work, after all @Bl4Cc4t still doesn't have it in their end
![image](https://user-images.githubusercontent.com/93687310/162330928-c993630a-96ea-4068-bdd9-d18e8e53f1d9.png)

**Comment by ni1chigo2115** [comment]
For the community button, did it show up for everyone?
I can see it now, too, and there is no mention here of any long term problems with it, so I'm going to CLOSED it.

**Comment by Bl4Cc4t** [comment]
I still don't have it, I only have a "Twitter circle" now. Good to know that it appeared for you at least, thanks for checking back
