### ISSUE TITLE
Legacy profile layout broke

### ISSUE THREAD

**Issue by CinderBH** [Bl4Cc4t/GoodTwitter2#478]
**Please check the following before you continue**
- [X] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [X] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [X] Checked if the issue has not been reported before

**Describe the bug**
What the title says. Sorry it happened right after an update...

**Screenshots**
https://i.imgur.com/LuO8XMB.png

**Your configuration**
 - Browser: Firefox 104.0.2
 - Userscript Manager: Tampermonkey 4.7.6161

**Comment by Trit34** [comment]
Same for me (Vivaldi 5.4, TamperMonkey 4.16.1, GT2 0.0.40.4).

**Comment by Trit34** [comment]
@CinderBH Fixed in 0.0.40.5, now (duplicate of #474).

**Comment by Bl4Cc4t** [comment]
yep, this bug should already be fixed. please let me know if you have this problem with 0.0.40.5 as well @CinderBH

**Comment by CinderBH** [comment]
Yes, it has. Though I recommend checking #479.

**Comment by Trit34** [comment]
Broken again: the pictograms on the right (with the menu to follow, mute, block) is not showing anymore.
![Capture d’écran_2022-09-25_01-36-54](https://user-images.githubusercontent.com/90716575/192122323-1bb4538f-2fc7-4b76-89b6-1c7e24619384.png)

**Comment by Bl4Cc4t** [comment]
indeed. looks like they're changing some more things. never gets tiring fixing their stuff :V

**Comment by Trit34** [comment]
~~Still broken~~ Actually, it was hidden because if the “AdGuard Annoyances” filter list in uBlock Origin: these buttons are displayed when I disable this list.

**Comment by Bl4Cc4t** [comment]
they only disappeared/got replaced by an avatar if you went from one profile page to another one.
I doubt the annoyances filter list contains something so specific :D

**Comment by Trit34** [comment]
> they only disappeared/got replaced by an avatar if you went from one profile page to another one. **I doubt the annoyances filter list contains something so specific** :D

Well, after having disabled this list and reloaded the page of another account, the icons went back, so… ¯\\\_(ツ)\_/¯
